### PR TITLE
changed login ui

### PR DESCRIPTION
**Pull request by yonis9**
Hi, I've changed a bit the login UI, I hope you like it.

### CODE REVIEW

**Comment by priyanshbalyan** [comment]
@yonis9 Looks great! Can you change the background and particles color to something better? A white background with light blue particles would look great. Let me know if you are able to do it.

**Comment by yonis9** [comment]
@priyanshbalyan yeah, sure.

**Comment by yonis9** [comment]
Hi, I've changed the colors, let me know what you think.
Also, should I make a new pull request for the last changes or it's fine like that?

**Comment by priyanshbalyan** [comment]
Great work! No need to raise addtional pull requests.

**Comment by yonis9** [comment]
Cool, thanks!

**Pull request merged**
